"""
Streaming Output for Real-Time Clinical Note Processing
=========================================================
Demonstrates LCEL's built-in streaming capability for real-time clinical
analysis. Instead of waiting for the entire response, tokens appear as
they're generated — critical for clinical tools where users need immediate
feedback.

Shows three streaming patterns:
1. Basic token streaming with .stream()
2. Async streaming with .astream()
3. Streaming with intermediate step events via .astream_events()

Requires: OPENAI_API_KEY environment variable, langchain, langchain-openai
"""

import asyncio
import sys
import time

from dotenv import load_dotenv
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableLambda
from langchain_openai import ChatOpenAI

load_dotenv()


# --- Chain Setup ---

model = ChatOpenAI(model="gpt-4o-mini", temperature=0.2, streaming=True)
str_parser = StrOutputParser()

analysis_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        "You are a clinical analysis system. Provide a detailed clinical analysis "
        "of the presented case. Structure your response with clear sections:\n\n"
        "## Chief Complaint & HPI Summary\n"
        "## Key Findings\n"
        "## Assessment\n"
        "## Differential Diagnosis\n"
        "## Recommended Workup\n"
        "## Disposition\n\n"
        "Be thorough but concise. Use medical terminology appropriately.",
    ),
    ("human", "Analyze this clinical note:\n\n{note_text}"),
])

analysis_chain = analysis_prompt | model | str_parser


# --- Test Note ---

CLINICAL_NOTE: str = (
    "45-year-old female presents to the emergency department with acute onset left-sided "
    "chest pain and shortness of breath that started 6 hours ago while on a long-haul "
    "flight from London. Pain is pleuritic, sharp, worse with deep inspiration. She reports "
    "mild hemoptysis (streaked blood in sputum) twice. She was recently started on oral "
    "contraceptives 2 months ago. PMH: obesity (BMI 34), factor V Leiden heterozygous "
    "(diagnosed 5 years ago, no prior thrombotic events). Family history: mother had DVT at "
    "age 50. Vitals: BP 132/84, HR 112, RR 22, SpO2 92% on room air, Temp 99.1F. Exam: "
    "tachycardic, clear lungs, mild right calf swelling and tenderness. D-dimer 4.2 "
    "(normal <0.5). ABG: pH 7.48, pCO2 30, pO2 68. ECG: sinus tachycardia, S1Q3T3 pattern, "
    "right axis deviation."
)


# --- Pattern 1: Basic Synchronous Streaming ---

def demo_basic_streaming() -> None:
    """Stream tokens from the analysis chain in real time."""
    try:
        from rich.console import Console

        console = Console()
        use_rich = True
    except ImportError:
        use_rich = False

    if use_rich:
        console.print("\n[bold cyan]Pattern 1: Basic Token Streaming (.stream())[/bold cyan]")
        console.print("[dim]Tokens appear as they're generated by the LLM...[/dim]\n")

    start = time.time()
    token_count = 0

    for chunk in analysis_chain.stream({"note_text": CLINICAL_NOTE}):
        print(chunk, end="", flush=True)
        token_count += 1

    elapsed = time.time() - start
    print()  # Final newline

    if use_rich:
        console.print(f"\n[dim]Streamed {token_count} chunks in {elapsed:.2f}s[/dim]")
        console.print(
            f"[dim]Time to first token: ~{elapsed / max(token_count, 1) * 1000:.0f}ms per chunk[/dim]"
        )


# --- Pattern 2: Async Streaming ---

async def demo_async_streaming() -> None:
    """Async streaming — useful for web frameworks (FastAPI, etc.)."""
    try:
        from rich.console import Console

        console = Console()
        use_rich = True
    except ImportError:
        use_rich = False

    if use_rich:
        console.print("\n[bold cyan]Pattern 2: Async Streaming (.astream())[/bold cyan]")
        console.print("[dim]Non-blocking streaming for web applications...[/dim]\n")

    start = time.time()
    token_count = 0

    async for chunk in analysis_chain.astream({"note_text": CLINICAL_NOTE}):
        print(chunk, end="", flush=True)
        token_count += 1

    elapsed = time.time() - start
    print()

    if use_rich:
        console.print(f"\n[dim]Async streamed {token_count} chunks in {elapsed:.2f}s[/dim]")


# --- Pattern 3: Streaming with Events (shows pipeline steps) ---

async def demo_event_streaming() -> None:
    """Stream events from all chain steps — shows intermediate processing."""
    try:
        from rich.console import Console

        console = Console()
        use_rich = True
    except ImportError:
        use_rich = False

    # Add a preprocessing step so we have multiple chain events to observe
    def preprocess(input_dict: dict) -> dict:
        """Preprocessing step that we can observe in the event stream."""
        note = input_dict["note_text"]
        word_count = len(note.split())
        return {**input_dict, "word_count": word_count}

    chain_with_preprocessing = (
        RunnableLambda(preprocess).with_config({"run_name": "Preprocess"})
        | analysis_prompt.with_config({"run_name": "FormatPrompt"})
        | model.with_config({"run_name": "LLMCall"})
        | str_parser.with_config({"run_name": "ParseOutput"})
    )

    if use_rich:
        console.print("\n[bold cyan]Pattern 3: Event Streaming (.astream_events())[/bold cyan]")
        console.print("[dim]Shows events from each pipeline step...[/dim]\n")

    events_seen: set[str] = set()

    async for event in chain_with_preprocessing.astream_events(
        {"note_text": CLINICAL_NOTE},
        version="v2",
    ):
        event_type = event["event"]
        run_name = event.get("name", "")

        # Log unique event types as they occur
        event_key = f"{event_type}:{run_name}"
        if event_key not in events_seen and event_type in (
            "on_chain_start",
            "on_chain_end",
            "on_chat_model_start",
            "on_chat_model_stream",
        ):
            if event_type != "on_chat_model_stream":
                events_seen.add(event_key)
                if use_rich:
                    console.print(f"[yellow]Event: {event_type} | Step: {run_name}[/yellow]")

        # Stream the actual LLM tokens
        if event_type == "on_chat_model_stream":
            chunk_content = event["data"]["chunk"].content
            if chunk_content:
                print(chunk_content, end="", flush=True)

    print()

    if use_rich:
        console.print(
            f"\n[dim]Observed {len(events_seen)} unique pipeline events[/dim]"
        )


# --- FastAPI Integration Example (code only, not runnable) ---

FASTAPI_EXAMPLE: str = '''
# Example: How to integrate LCEL streaming with FastAPI
# This is reference code, not executed in this demo.

from fastapi import FastAPI
from fastapi.responses import StreamingResponse

app = FastAPI()

@app.post("/analyze")
async def analyze_note(note_text: str):
    """Stream clinical analysis tokens via Server-Sent Events."""
    async def token_generator():
        async for chunk in analysis_chain.astream({"note_text": note_text}):
            yield f"data: {chunk}\\n\\n"
        yield "data: [DONE]\\n\\n"

    return StreamingResponse(
        token_generator(),
        media_type="text/event-stream",
    )
'''


def main() -> None:
    """Run all streaming demos."""
    try:
        from rich.console import Console
        from rich.panel import Panel

        console = Console()
        use_rich = True
    except ImportError:
        use_rich = False

    if use_rich:
        console.print(
            Panel(
                CLINICAL_NOTE[:250] + "...",
                title="[bold]Clinical Note for Streaming Analysis[/bold]",
                border_style="cyan",
            )
        )

    # Pattern 1: Basic streaming
    demo_basic_streaming()

    if use_rich:
        console.print(f"\n[bold]{'=' * 80}[/bold]")

    # Pattern 2 & 3: Async streaming
    # Run both async patterns
    asyncio.run(demo_async_streaming())

    if use_rich:
        console.print(f"\n[bold]{'=' * 80}[/bold]")

    asyncio.run(demo_event_streaming())

    # Show FastAPI integration reference
    if use_rich:
        console.print(f"\n[bold]{'=' * 80}[/bold]")
        console.print("[bold cyan]Bonus: FastAPI Integration Pattern[/bold cyan]")
        console.print(
            Panel(
                FASTAPI_EXAMPLE,
                title="FastAPI Streaming Endpoint",
                border_style="dim",
            )
        )


if __name__ == "__main__":
    main()


# --- Sample Output ---
#
# Pattern 1: Basic Token Streaming (.stream())
# Tokens appear as they're generated by the LLM...
#
# ## Chief Complaint & HPI Summary
# 45-year-old female presenting with acute left-sided pleuritic chest pain and
# dyspnea of 6 hours duration, onset during a long-haul flight. Associated
# hemoptysis (blood-streaked sputum x2). Significant risk factors: recent OCP
# initiation (2 months), known factor V Leiden heterozygosity, obesity, and
# prolonged immobilization during flight.
#
# ## Key Findings
# - Tachycardia (HR 112), tachypnea (RR 22), hypoxia (SpO2 92%)
# - Right calf swelling and tenderness (suggests DVT)
# - Markedly elevated D-dimer (4.2, >8x normal)
# - ABG: respiratory alkalosis with hypoxemia (pO2 68)
# - ECG: S1Q3T3 pattern and right axis deviation (classic PE findings)
#
# ## Assessment
# Clinical presentation is highly consistent with acute pulmonary embolism,
# likely with concurrent deep vein thrombosis (right lower extremity). The
# constellation of pleuritic chest pain, hemoptysis, hypoxia, elevated D-dimer,
# and classic ECG changes in a patient with multiple VTE risk factors
# (Factor V Leiden, OCPs, prolonged air travel, obesity) makes PE the leading
# and most dangerous diagnosis.
#
# ## Differential Diagnosis
# 1. Pulmonary embolism (most likely)
# 2. Pneumothorax
# 3. Pneumonia with parapneumonic effusion
# 4. Acute coronary syndrome (less likely given pleuritic nature)
# 5. Costochondritis (diagnosis of exclusion)
#
# ## Recommended Workup
# - CT pulmonary angiography (CTPA) — definitive test for PE
# - Lower extremity venous duplex ultrasound (assess for DVT)
# - Echocardiogram (assess right heart strain if PE confirmed)
# - CBC, BMP, coagulation studies
# - Troponin and BNP (prognostic markers in PE)
#
# ## Disposition
# Admit to monitored bed. Initiate therapeutic anticoagulation (heparin drip)
# pending CTPA results given high clinical suspicion. If massive PE with
# hemodynamic compromise, consider thrombolysis or interventional radiology.
#
# Streamed 142 chunks in 3.41s
